### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by kazegawa** [vexanium/DApps#1]
I already tried on DApp Browser inside the Android APP, not showing anything after click login button

**Comment by kanggunawans** [comment]
Yes, I already tried too on DApp Browser inside the Android App, not showing anything after click login button

It hasn't been updated in a long time, this line doesn't work on mobile.

pe.getWalletWithAccount (). then ((res) => (
if (! res) {
Not connected();
back;
}
account = res.data.account;
onConnected ();

**Comment by YudaAdiPratama** [comment]
> I already tried on DApp Browser inside the Android APP, not showing anything after click login button

Hi @kazegawa 
for reference you can see [https://github.com/vexanium/DApps/tree/master/dbrowser-int#readme](https://github.com/vexanium/DApps/tree/master/dbrowser-int#readme)

**Comment by YudaAdiPratama** [comment]
> pe.getWalletWithAccount

there is a bug in vexwallet version 1.1.6.6 

latest version will be updated soon
